services:
#Service odoo toma el Dockerfile de ./build/odoo
 odoo1:
  build: ./odoo
  hostname: odoo1
  env_file: 
  - "odoo/odoo.env"
  ports:
  - "8069:8069"
  #Mapeo del directorio de la MV en el container
  volumes:
  - ~/odoo/src:/opt/odoo/src
  networks:
   nginx_odoo:
    ipv4_address: 192.168.201.101
 odoo2:
  build: ./odoo
  hostname: odoo2
  env_file: 
  - "odoo/odoo.env"
  ports:
  - "8070:8069"
  #Mapeo del directorio de la MV en el container
  volumes:
  - ~/odoo/src:/opt/odoo/src
  networks:
   nginx_odoo:
    ipv4_address: 192.168.201.102
 nginx:
  build: ./nginx
  hostname: nginx
  ports:
  - "80:80"
  networks:
   nginx_odoo:
    ipv4_address: 192.168.201.100
  volumes:
  - nginx_conf:/etc/nginx
networks:
  nginx_odoo:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.201.0/24
volumes:
  nginx_conf:
   
