FROM debian:13

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    vim \
    curl \
    iputils-ping \
    net-tools \
    nano \
    wget \
    procps \
    python3 \
    python3-dev \
    python3-pip \
    python3-phonenumbers \
    postgresql-client \
    build-essential \
    libxml2-dev \
    libxslt1-dev \
    libldap2-dev \
    libsasl2-dev \
    libtiff5-dev \
    libopenjp2-7-dev \
    zlib1g-dev \
    libfreetype6-dev \
    liblcms2-dev \
    libwebp-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libxcb1-dev \
    libpq-dev \
    libffi-dev \
    libjpeg62-turbo-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*
